//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activeproductitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activeproductitem()
        {
            this.claims = new HashSet<claim>();
            this.claimuploaddocuments = new HashSet<claimuploaddocument>();
            this.productproviderpayments = new HashSet<productproviderpayment>();
            this.productredemptionlogs = new HashSet<productredemptionlog>();
        }
    
        public int ActiveProductItems_ID { get; set; }
        public int Consumer_ID { get; set; }
        public int Product_ID { get; set; }
        public string activeProductItemPolicyNum { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public decimal productValue { get; set; }
        public int duration { get; set; }
        public Nullable<System.DateTime> activeProductItemStartDate { get; set; }
        public Nullable<int> transactionlocation { get; set; }
        public Nullable<System.DateTime> activeProductItemEndDate { get; set; }
        public string PurchaseConfirmationDocPath { get; set; }
    
        public virtual consumer consumer { get; set; }
        public virtual product product { get; set; }
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claim> claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimuploaddocument> claimuploaddocuments { get; set; }
        public virtual location location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productproviderpayment> productproviderpayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productredemptionlog> productredemptionlogs { get; set; }
    }
}
