//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chrisviewconsumeractiveproduct
    {
        public int ActiveProductItems_ID { get; set; }
        public Nullable<System.DateTime> activeProductItemStartDate { get; set; }
        public int Consumer_ID { get; set; }
        public int Product_ID { get; set; }
        public int duration { get; set; }
        public decimal productValue { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public int InsuranceType_ID { get; set; }
        public Nullable<decimal> ipCoverAmount { get; set; }
        public string UnitTypeDescription { get; set; }
    }
}
