//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public claim()
        {
            this.claimuploaddocuments = new HashSet<claimuploaddocument>();
        }
    
        public int Claim_ID { get; set; }
        public Nullable<int> Consumer_ID { get; set; }
        public Nullable<int> ActiveProductItems_ID { get; set; }
        public string capturedClaimFormDataJson { get; set; }
        public Nullable<System.DateTime> claimDate { get; set; }
        public string claimStatus { get; set; }
        public string claimPaymentFinalised { get; set; }
    
        public virtual activeproductitem activeproductitem { get; set; }
        public virtual consumer consumer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimuploaddocument> claimuploaddocuments { get; set; }
    }
}
