//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientswithunprocessedapplication
    {
        public int idConsumer { get; set; }
        public string clientName { get; set; }
        public Nullable<int> Consumer_ID { get; set; }
        public Nullable<decimal> claimRate { get; set; }
        public string RiskCategory { get; set; }
        public long numUnprocessed { get; set; }
    }
}
