//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumerpreference
    {
        public int pRef { get; set; }
        public int consumerRef { get; set; }
        public int Product_ID { get; set; }
        public long numPurchase { get; set; }
    }
}
