//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumerriskvalue
    {
        public int idConsumer { get; set; }
        public Nullable<int> Consumer_ID { get; set; }
        public Nullable<int> age { get; set; }
        public string ageGroup { get; set; }
        public Nullable<int> ageRiskValue { get; set; }
        public string gender { get; set; }
        public Nullable<int> genderRiskValue { get; set; }
        public string maritalStatus { get; set; }
        public Nullable<int> maritalStatusRiskValue { get; set; }
        public string employmentStatus { get; set; }
        public Nullable<int> employmentStatusRiskValue { get; set; }
        public Nullable<decimal> claimRate { get; set; }
        public Nullable<int> claimRiskValue { get; set; }
        public string RiskCategory { get; set; }
        public Nullable<int> OverallRiskValue { get; set; }
        public string purchasedProducts { get; set; }
        public Nullable<int> numUnprocessed { get; set; }
        public string consumerName { get; set; }
        public string purchasedProductIDs { get; set; }
    
        public virtual consumer consumer { get; set; }
    }
}
