//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentspecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documentspecification()
        {
            this.claimuploaddocuments = new HashSet<claimuploaddocument>();
        }
    
        public int document_ID { get; set; }
        public int Product_ID { get; set; }
        public string documentName { get; set; }
        public string documentDescription { get; set; }
        public string docPreferredFormat { get; set; }
        public string docPreparationRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimuploaddocument> claimuploaddocuments { get; set; }
        public virtual product product { get; set; }
    }
}
