//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class individualconsumerprofilerrawdata
    {
        public int Consumer_ID { get; set; }
        public int User_ID { get; set; }
        public long numPurchases { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> numClaims { get; set; }
        public Nullable<decimal> ratio { get; set; }
    }
}
