//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insuranceproduct
    {
        public int InsuranceProduct_ID { get; set; }
        public int ProductProvider_ID { get; set; }
        public int InsuranceType_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<decimal> ipCoverAmount { get; set; }
        public Nullable<decimal> ipUnitCost { get; set; }
        public Nullable<int> ipUnitType { get; set; }
        public Nullable<int> ipMinimunNoOfUnits { get; set; }
        public string ipClaimInfoPath { get; set; }
        public Nullable<System.DateTime> claimTimeframe { get; set; }
        public string policyNumberApiLink { get; set; }
        public string ApiKey { get; set; }
        public string claimContactNo { get; set; }
        public string claimFormPath { get; set; }
        public Nullable<int> claimtemplate_ID { get; set; }
    
        public virtual claimtemplate claimtemplate { get; set; }
        public virtual unittype unittype { get; set; }
        public virtual productprovider productprovider { get; set; }
        public virtual insurancetype insurancetype { get; set; }
        public virtual product product { get; set; }
    }
}
