//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notificationlog
    {
        public int NotificationLog_ID { get; set; }
        public string notificationType { get; set; }
        public int notificationReceiver { get; set; }
        public System.DateTime notificationDateSent { get; set; }
    
        public virtual user user { get; set; }
    }
}
