//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.activeproductitems = new HashSet<activeproductitem>();
            this.documentspecifications = new HashSet<documentspecification>();
            this.insuranceproducts = new HashSet<insuranceproduct>();
            this.processapplications = new HashSet<processapplication>();
        }
    
        public int Product_ID { get; set; }
        public int ProductProvider_ID { get; set; }
        public Nullable<int> ProductType_ID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string detailedDescription { get; set; }
        public string productPolicyDocPath { get; set; }
        public Nullable<bool> isAvailableForPurchase { get; set; }
        public Nullable<decimal> salesTargetAmount { get; set; }
        public Nullable<decimal> ratingAverage { get; set; }
        public Nullable<int> numTimesRated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activeproductitem> activeproductitems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentspecification> documentspecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insuranceproduct> insuranceproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<processapplication> processapplications { get; set; }
        public virtual productprovider productprovider { get; set; }
        public virtual producttype producttype { get; set; }
    }
}
