//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productprovider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productprovider()
        {
            this.insuranceproducts = new HashSet<insuranceproduct>();
            this.products = new HashSet<product>();
            this.productproviderpayments = new HashSet<productproviderpayment>();
        }
    
        public int ProductProvider_ID { get; set; }
        public int User_ID { get; set; }
        public string ppCompanyName { get; set; }
        public string ppVATnumber { get; set; }
        public string ppFaxNumber { get; set; }
        public string ppAddress { get; set; }
        public Nullable<int> lastAssignedPolicyNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insuranceproduct> insuranceproducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productproviderpayment> productproviderpayments { get; set; }
    }
}
