//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productredemptionlog
    {
        public int Voucher_ID { get; set; }
        public int ActiveProductItems_ID { get; set; }
        public decimal transactionAmount { get; set; }
    
        public virtual activeproductitem activeproductitem { get; set; }
        public virtual voucher voucher { get; set; }
    }
}
