//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productproviderpayment
    {
        public int Productproviderpayment_ID { get; set; }
        public Nullable<int> ProductProvider_ID { get; set; }
        public Nullable<int> ActiveProductItems_ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> AmountToPay { get; set; }
        public Nullable<bool> hasBeenPayed { get; set; }
        public Nullable<System.DateTime> DatePayed { get; set; }
    
        public virtual activeproductitem activeproductitem { get; set; }
        public virtual productprovider productprovider { get; set; }
    }
}
