//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincialinsurancetypesale
    {
        public int ActiveProductItems_ID { get; set; }
        public int InsuranceType_ID { get; set; }
        public string insuranctTypeDescription { get; set; }
        public string Province { get; set; }
        public Nullable<decimal> sales { get; set; }
    }
}
