//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resellersendvouchergenderspecific
    {
        public int VoucherSentTo { get; set; }
        public string date_format_vouchertransaction_transactionDate___Y__b__ { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> sales { get; set; }
    }
}
