//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resellersalespermonth
    {
        public int VoucherSentTo { get; set; }
        public System.DateTime transactionDate { get; set; }
        public int Sender_ID { get; set; }
        public Nullable<decimal> sold { get; set; }
    }
}
