//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resvouchersendvessold
    {
        public int User_ID { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public int TransactionType_ID { get; set; }
        public System.DateTime transactionDate { get; set; }
    }
}
