//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemadmin
    {
        public int SystemAdmin_ID { get; set; }
        public int User_ID { get; set; }
        public string systemAdminOTP { get; set; }
        public Nullable<bool> systemAdminHasTwoPartAuth { get; set; }
    
        public virtual user user { get; set; }
    }
}
