//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.claimuploaddocuments = new HashSet<claimuploaddocument>();
            this.consumers = new HashSet<consumer>();
            this.contactlists = new HashSet<contactlist>();
            this.contactlists1 = new HashSet<contactlist>();
            this.notificationlogs = new HashSet<notificationlog>();
            this.productproviders = new HashSet<productprovider>();
            this.resellers = new HashSet<reseller>();
            this.systemadmins = new HashSet<systemadmin>();
            this.validators = new HashSet<validator>();
            this.vouchers = new HashSet<voucher>();
            this.vouchertransactions = new HashSet<vouchertransaction>();
            this.vouchertransactions1 = new HashSet<vouchertransaction>();
        }
    
        public int User_ID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public string userContactNumber { get; set; }
        public string userPassword { get; set; }
        public Nullable<bool> userIsActive { get; set; }
        public Nullable<int> userType { get; set; }
        public string userActivationType { get; set; }
        public string IDnumber { get; set; }
        public string IdDocumentPath { get; set; }
        public Nullable<System.DateTime> IdDocumentLastUpdated { get; set; }
        public Nullable<System.DateTime> timeStap { get; set; }
        public string resetPasswordKey { get; set; }
        public string blockchainAddress { get; set; }
        public string otpCode { get; set; }
        public Nullable<int> otpRetryCount { get; set; }
        public Nullable<System.DateTime> otpExpirationTime { get; set; }
        public Nullable<System.DateTime> otpNextAllowedTime { get; set; }
        public Nullable<System.DateTime> otpRecordCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<claimuploaddocument> claimuploaddocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumer> consumers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactlist> contactlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactlist> contactlists1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notificationlog> notificationlogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productprovider> productproviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reseller> resellers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<systemadmin> systemadmins { get; set; }
        public virtual usertype usertype1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validator> validators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voucher> vouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vouchertransaction> vouchertransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vouchertransaction> vouchertransactions1 { get; set; }
    }
}
