//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class validator
    {
        public int Validator_ID { get; set; }
        public int User_ID { get; set; }
        public string validatiorCompany { get; set; }
        public string validatorLicenseNumber { get; set; }
        public string validatorLicenseProvider { get; set; }
        public Nullable<System.DateTime> validatorValidUntil { get; set; }
        public string validatorVATNumber { get; set; }
        public string validatorAddress { get; set; }
        public string validatorBankName { get; set; }
        public string validatorBankAccNumber { get; set; }
        public string validatorBankBranchName { get; set; }
        public string validatorBankBranchCode { get; set; }
    
        public virtual user user { get; set; }
    }
}
