//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vouchertransaction
    {
        public int Voucher_ID { get; set; }
        public int VoucherSentTo { get; set; }
        public int Sender_ID { get; set; }
        public int Receiver_ID { get; set; }
        public int TransactionType_ID { get; set; }
        public decimal transactionAmount { get; set; }
        public string transactionDescription { get; set; }
        public System.DateTime transactionDate { get; set; }
    
        public virtual transactiontype transactiontype { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual voucher voucher { get; set; }
        public virtual voucher voucher1 { get; set; }
    }
}
