//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NanofinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public voucher()
        {
            this.productredemptionlogs = new HashSet<productredemptionlog>();
            this.vouchertransactions = new HashSet<vouchertransaction>();
            this.vouchertransactions1 = new HashSet<vouchertransaction>();
        }
    
        public int Voucher_ID { get; set; }
        public int VoucherType_ID { get; set; }
        public int User_ID { get; set; }
        public decimal voucherValue { get; set; }
        public Nullable<System.DateTime> voucherCreationDate { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<System.DateTime> OTPtimeStap { get; set; }
        public string QRdata { get; set; }
        public Nullable<System.DateTime> QRtimeStap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productredemptionlog> productredemptionlogs { get; set; }
        public virtual user user { get; set; }
        public virtual vouchertype vouchertype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vouchertransaction> vouchertransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vouchertransaction> vouchertransactions1 { get; set; }
    }
}
